### ISSUE TITLE
Implementere tjenesten som henter årsregnskapet ut og lager representasjonen

### ISSUE THREAD

**Issue by lillelars** [nordicsmartgovernment/nordicsmartgovernment#10]
- [x] Generate code from specification
- [x] Map from XML to DTO for persistance
- [x] Map from persistance-DTO to generated
- [x] Implement generated controllers
- [x] Unit tests

**Comment by NilsOveTen** [comment]
3 values still needs to be mapped, seems to not have corresponding values in the input-file. They have been commented with "TODO"

Missing values:
- Virksomhet.navn
- Virksomhet.levertAarsregnskap
- Regnskapsprinsipper.regskapsregler
