### ISSUE TITLE
Create Bank Statement entry in ISO 20022 format through API

### ISSUE THREAD

**Issue by lillelars** [nordicsmartgovernment/nordicsmartgovernment#13]
From Req-Spec:
https://github.com/Informasjonsforvaltning/behov/issues/125

as: a system user (another system used in the PoCs)
I want: the bank statement in ISO 20022-format represented in a common XBRL GL format
so that: I can relate information from eInvoices, eReceipts and bank account statements for later retrieval

Related to epic: #4

Lenke til design: N/A
Lenke til løsningsarkitektur:

Things to take into account for the developer

* Create a target information model in XBRL GL
* refactor the existing ISO 20022-to-XBRL GL transformation

**Comment by joebrreg** [comment]
camt 53: https://www.iso20022.org/sites/default/files/documents/messages/camt/schemas/camt.053.001.08.zip

**Comment by stigbd** [comment]
Spesifikasjonen er lagd og ligger i https://github.com/nordicsmartgovernment/nordicsmartgovernment/tree/feature/bank_statement_API/Issue13

**Comment by ekoskent** [comment]
XSLT transformer for Camt053 messages added to github xslf-folder file called: camt_053_xbrlgl.xslt.
