### ISSUE TITLE
Improving code to detecting what type of invoice we receive

### ISSUE THREAD

**Issue by lillelars** [nordicsmartgovernment/nordicsmartgovernment#15]
- [x] investigate whether there is a content type we can use

- [x] is it a purchase or a sales invoice?

- [x] create mapping from document type to documents

- [x] create tests

**Comment by stigbd** [comment]
From an email by Elina:
>About the document types.. We need to separate this into to things :
>1)	Document identifier: identifies the schema used. I think we should comply with the notation used in PEPPOL: https://www.oasis-open.org/committees/download.php/40926/PEPPOL%20D8_2%20-%20Attachment%20I%20%20BusDox%20Common%20Definitions.pdf chapter 5.2., e.g. for UBL 2.1 it would be: urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##UBL-2.1
>2)	Content type / Mime type: identifies the file format. Basically for all our structural documents in the ref. implementation it’s “application/xml” or “text/xml” but might as well be “application/json”. Also the API have to support non-structural mime types such as pdf, png etc..

**Comment by frodegill** [comment]
The document linked above doesn't have a chapter 5.2?

**Comment by lillelars** [comment]
@ekoskent can you see the comment above

**Comment by ekoskent** [comment]
Sorry it was 2.5.
