### ISSUE TITLE
konfigurere og sett opp prod-miljø med korrekt sertifikater osv

### ISSUE THREAD

**Issue by lillelars** [nordicsmartgovernment/nordicsmartgovernment#28]
Sette opp sertifikater og bestille url:

https://nsg.fellesdatakatalog.brreg.no

**Comment by bgrova** [comment]
Slik jeg oppfattet konklusjonen av diskusjon på sprintplanlegging, er "prod" miljøet et demomiljø. Jeg kaller derfor prosjektet i GCP nsg-demo.
