### ISSUE TITLE
Verifiser om vi trenger backup av DB eller ikke

### ISSUE THREAD

**Issue by lillelars** [nordicsmartgovernment/nordicsmartgovernment#29]

**Comment by sindresandvik2** [comment]
@stigbd  Kan du avgjere dette?

**Comment by lillelars** [comment]
@stigbd Tar opp dette med NSG-folka (David?)

**Comment by stigbd** [comment]
Har sendt e-post til David for avklaring.

**Comment by stigbd** [comment]
Har etter samtale med David kome fram til at backup av DB ikkje er nødvendig nå.
