### ISSUE TITLE
Bestemme domenenavn og bestille dette

### ISSUE THREAD

**Issue by lillelars** [nordicsmartgovernment/nordicsmartgovernment#33]
- [x] Stig bestemmer domenenavn

- [x] Bjørn bestiller routing hos de som eier data.brreg.no (dette gjorde vi for begrepspubliserr)

**Comment by lillelars** [comment]
@bgrova url skal bli: "https://data.brreg.no/regnskapsregisteret"

**Comment by bgrova** [comment]
i følge @stigbd er dette riktig url

**Comment by bgrova** [comment]
Vi må bestemme hva url-ene til utviklings- og testmiljøene skal være.
Den mest logiske strukturen er https://data.ut1.brreg.no/regnskapsregisteret
etc...
Men jeg tror kanskje denne kan skape noen utfordringer med oppsett av ruting, siden *.ut1.brreg.no ellers ruter til Openshift-miljøene.

En enklere, men ikke fullt så elegant løsning, kan være f eks:
https://ut1.rreg.brreg.no
etc.
Her blir konfigurasjon av ruting enklere, til gjengjeld krever det at vi bestiller et ekstra SSL-sertifikat for *.rreg.brreg.no (eller hva nå adressen måtte bli)

**Comment by bgrova** [comment]
Fikk beskjed fra FB at de ikke ønsker Regnskapsregisteret publisert på adressen "https://data.brreg.no/regnskapsregisteret", og at de vil komme med en annen adresse.
Har derfor bedt IT vente med oppsett i BigIP til dette er avklart.

**Comment by bgrova** [comment]
FB har bestemt at adressen skal være
https://beta.brreg.no/fou/Regnskapsregisteret

De har kontakt med IU angående aktivisering av denne adressen.

**Comment by bgrova** [comment]
Har oppdatert saken om bestilling av ruting til denne adressen. Fikk henvendelse fra FB om den i dag.

**Comment by sskagemo** [comment]
Dette issuet tilhører et annet prosjekt, og der er det løst. Lukker denne.
