### ISSUE TITLE
Bestemme og sette opp CI/CD

### ISSUE THREAD

**Issue by lillelars** [nordicsmartgovernment/nordicsmartgovernment#34]
Se confluence for oppskrift og beskrivelse:
https://confluence.brreg.no/display/APP/Opprette+ny+%28mikro%29tjeneste
Vi skal gjøre 3) ?

- [X] Lag kildekoderepository i GitHub

- [x] Sett opp webhooks i Github kildekoderepository

- [x] Definer CI/CD i fdk-config

- [x] Bestemme konfigurasjon for tjenesten i de ulike miljøene (ut1, st1, demo etc) (JENKINS)

**Comment by joebrreg** [comment]
@bgrova Det er en feil i ut1
