### ISSUE TITLE
Sett opp DB inkludert backup - PROD

### ISSUE THREAD

**Issue by lillelars** [nordicsmartgovernment/nordicsmartgovernment#38]

**Comment by bgrova** [comment]
vurdere å kjøre managed Mongodb i stedet for Mongodb i Kubernetes-container.
https://console.cloud.google.com/marketplace/browse?q=mongodb&authuser=2&folder&organizationId=382284307604

@stigbd

**Comment by lillelars** [comment]
@bgrova dobbelsjekker du ift backup? også closer tasken hvis den er ferdig

**Comment by bgrova** [comment]
Backup satt på to nivåer:
* Nattlig snapshot hver natt
* Labler backupweeks:8 og snapshotdays:30 satt. Dette gjør at diskene blir kopiert til backup-prosjektet (som ligger i et annet datasenter) hver natt. Snapshots blir tatt vere på i 30 dager, i tillegg til at en uklig backup blir tatt vare på i 8 uker.
