### ISSUE TITLE
Mangler mapping for felter ang. IFRS

### ISSUE THREAD

**Issue by NilsOveTen** [nordicsmartgovernment/nordicsmartgovernment#43]
IFRS inndata:
- ifrs_selskap
- ifrs_konsern

IFRS utdata
- IFRS
- forenkletAnvendelseIFRS
- regnskapslovenAlminneligRegler

**Comment by NilsOveTen** [comment]
Fjerner navn-feltet

**Comment by lillelars** [comment]
Trenger informasjon om hvordan vi skal fylle ut Enum'en. Venter på svar fra FB

**Comment by NilsOveTen** [comment]
Verifisert i UT1 av Christine Hovstøl
