### ISSUE TITLE
Add basic auth to openAPI specifications where this is relevant

### ISSUE THREAD

**Issue by stigbd** [nordicsmartgovernment/nordicsmartgovernment#45]
A little help to solve this is the following guidance:
https://swagger.io/docs/specification/authentication/basic-authentication/

**Comment by ekoskent** [comment]
suggest to add the basic auth to all APIs. Could we also check the password especially in cases where data is being added or  edited as we should be able to have some control over the data that is in the reference implementation?

**Comment by frodegill** [comment]
There is no authentication now
