### ISSUE TITLE
[USER STORY] Update business transaction data

### ISSUE THREAD

**Issue by stigbd** [nordicsmartgovernment/nordicsmartgovernment#46]
As: a system user (another system used in the PoCs)
I wish: to update the existing business transaction details
So that: the system can have most complete set of data that is available about the transaction

Copy of https://github.com/Informasjonsforvaltning/behov/issues/155

**Comment by stigbd** [comment]
I have added a patch operation to the transaction api that should support update. It is supposed to be compliant to https://tools.ietf.org/html/rfc5261 and a possible implementation to be consider should be https://github.com/dnault/xml-patch

**Comment by frodegill** [comment]
Patch is now implemented, according to RFC5261. Example XML for patching XBRL GL entity identifier:

<diff xmlns:xbrli="http://www.xbrl.org/2003/instance">
  <replace sel="xbrli:xbrl/xbrli:context/xbrli:entity/xbrli:identifier/text()">Patched!</replace>
</diff>

**Comment by sindresandvik2** [comment]
Testet OK i UT1 sammen med Frode!   
Replace , Add og Remove ble testet OK vha Postman
Replace-funksjonen er også implementert i en Unit Test

Dette eposet lukker også # 48, 49 0g 51
