### ISSUE TITLE
Nøkkeltall fra årsregnskapet for siste regnskapsår som åpne data (MVP)

### ISSUE THREAD

**Issue by lillelars** [nordicsmartgovernment/nordicsmartgovernment#5]
Fra behov:
https://github.com/Informasjonsforvaltning/behov/issues/180

Som: konsument (system) av regnskapsdata
Ønsker jeg: maskinell tilgang til nøkkeltall fra siste regnskapsår som er innrapportert til Regnskapsregisteret
Slik at: jeg kan benytte de ferskeste regnskapstall som er levert i mine tjenester (applikasjoner)

Lenke til trådskisser: N/A
Lenke til overordna arkitektur: https://informasjonsforvaltning.github.io/SA_Informasjonsforvaltning/f4212a30-53d0-4c27-a682-4f88d6c692c8/views/307b9dcf-4a6d-4d73-8f27-73aea88b6dbe.html
Løsningsmodell: https://confluence.brreg.no/pages/viewpage.action?pageId=124885464

Se informasjonsmodell:
https://modeller.brreg.no/informasjonsmodeller/SM-Regnskapsregisteret/Regnskapsregisteret.html

**Comment by sskagemo** [comment]
Denne brukerhistorien er levert (annet prosjekt).
