### ISSUE TITLE
Lenkede data fra regnskapsdata

### ISSUE THREAD

**Issue by joebrreg** [nordicsmartgovernment/nordicsmartgovernment#50]
Kommer fra behov: https://github.com/Informasjonsforvaltning/behov/issues/320

Som: konsument av lenkede data
Ønsker jeg å: få lenkede data i RDF fra regnskapsdata
Slik at: jeg kan lenke data fra RR (regnskap), ER (enhet), Kartverkets Adm.grenser(kommune) og utenlandske registre for å oppnå best mulig datakvalitet.

**Comment by sskagemo** [comment]
Dette ble løst som en demo i et annet prosjekt.
