### ISSUE TITLE
The APIs don’t take into consideration the owner of the data

### ISSUE THREAD

**Issue by stigbd** [nordicsmartgovernment/nordicsmartgovernment#52]
The parameter companyID should be added everywhere in order to know who is the owner of the data. There may be multiple test companies data in the sandbox and we need to be able to split them. Also in real life use the companyID is key.

**Comment by stigbd** [comment]
OwnerCompanyId must be either a path-parameter or a (required) query-parameter. And response body gets another (meta-)property: 
components:
  schemas:
    InvoiceDocument:
      type: object
      properties:
        ownerCompanyID:
	  type: string
	Invoice:
	  type: object

**Comment by ekoskent** [comment]
@stigbd could you clarify the purpose of the above listed (meta-)property?
