### ISSUE TITLE
Refactor to one API for different types of vouchers

### ISSUE THREAD

**Issue by stigbd** [nordicsmartgovernment/nordicsmartgovernment#53]
I would suggest we give up the separate get/post APIs of different vouchers and rather create one API “get/post voucher” with a param of defined list for voucher type

**Comment by stigbd** [comment]
If the rationale for this is a future "get all vouchers" request, I very much understand your suggestion. Otherwise I prefer keeping our specific apis as-is.

**Comment by ekoskent** [comment]
Should we ask for feedback from the system vendors for this one?
