### ISSUE TITLE
Invoices API: Recognize purchase vs sales orders

### ISSUE THREAD

**Issue by stigbd** [nordicsmartgovernment/nordicsmartgovernment#56]
The API does not recognize purchase vs sales orders (with the current approach of having an API per voucher type we should then have separate APIs for purchase and sales invoices). Any how for the processing also it has to be known as the accounting handling (done by the transformers) is different

**Comment by stigbd** [comment]
As of now, our service does a "best effort" guess as to what kind of invoice it is dealing with. As you note, it is not 100%. But when we generalize our API to accept Vouchers, and the voucher type is explicitly given ("Purchase invoice" or "Sales invoice"), this issue should be resolved.

**Comment by frodegill** [comment]
Direction detection is now improved, but still far from perfect. (It now depends on namespaces, not namespace prefixes as before)
