### ISSUE TITLE
Etablere teknisk infrastruktur

### ISSUE THREAD

**Issue by lillelars** [nordicsmartgovernment/nordicsmartgovernment#6]
CI/CD:
- [x] Jenkins

- [x] Etablere config Repo

- [x] Etablere nytt Kubernetes-cluster

Dette skal dokumenteres hvordan blir gjort (i confluence)

**Comment by bgrova** [comment]
Har opprettet to cluster:
rreg-dev
rreg-prod

Dokumentasjon i Confluence:
https://confluence.brreg.no/display/APP/Opprette+ny+%28mikro%29tjeneste
