### ISSUE TITLE
Implementere Servicetest 

### ISSUE THREAD

**Issue by lillelars** [nordicsmartgovernment/nordicsmartgovernment#8]
- [x] Implement tests with docker images

- [x] Test for getByOrgnr

- [x] Test for getById

- [x] Kjøre på Jenkins

- [x] Støtte for brukernavn/passord i MongoDB

- [x] Dokumentere dette i confluence (Bjørn oppretter en side, Nils Ove kan dokumentere)

**Comment by bgrova** [comment]
Confluence-side for dokumentasjon: https://confluence.brreg.no/display/APP/Oppsett+av+Servicetest
